[package]
name = "mtwcl"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
image = "0.24.9"
include_dir = "0.7.3"
termimad = "0.29.1"
viuer = "0.7.1"
